Fix printf format errors found by gcc now that it can check
Fixes:
os/config.c: In function ‘config_parse_nameVal’:
os/config.c:417:5: warning: too few arguments for format
os/config.c: In function ‘config_parse_int’:
os/config.c:458:6: warning: too few arguments for format

Requires passing parm arguments around in order to provide parameter
names with problems in the error messages

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Reviewed-by: Jeremy Huddleston <jeremyhu@apple.com>